[[main]]
  name = "About"
  url = "/about/"
  weight = 5

[[main]]
  name = "News"
  url = "/posts/"
  weight = 10

[[main]]
  name = "Projects"
  url = "/projects/"
  weight = 12

[[main]]
  name = "Cognitive Bias"
  url = "/cognitive-bias/"
  weight = 15

[[main]]
  name = "Contacts"
  url = "/contacts/"
  weight = 20



# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Categories"
   pageRef = "categories"
   weight = 20
